name: socketlabs
version: 0.0.2
description: An API client for the SocketLabs email service.
repository: https://github.com/enyo/socketlabs
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  http: ^0.12.0
  logging: ^0.11.4
  meta: ^1.2.0

dev_dependencies:
  pedantic: ^1.9.0
  mockito: ^4.1.2
  test: ^1.15.0

  # pedantic: ^1.10.0-nullsafety.1
  # test: ^1.16.0-nullsafety.5
# dependency_overrides:
#   # Required for null safety
#   http:
#     git: https://github.com/dart-lang/http.git
#   http_parser:
#     git: https://github.com/dart-lang/http_parser.git
