name: socketlabs
version: 0.1.0
description: >-
  An API client for the SocketLabs email service, that allows you to send
  emails using their REST API.
repository: https://github.com/enyo/socketlabs
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  logging: "^1.0.0"

dev_dependencies:
  build_runner: ^2.1.7
  mocktail: ^0.2.0
  test: ^1.20.0
  lints: ^1.0.1
