name: socketlabs
version: 0.1.0-nullsafety.0
description: >
  A dart API client for the SocketLabs email service.
  Connect to your SocketLabs account and send emails with a simple API.
repository: https://github.com/enyo/socketlabs
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  http: ^0.13.0-nullsafety.0
  logging: ^1.0.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  # mockito: ^5.0.0-nullsafety.0 # Doesn't exist yet.
  test: ^1.16.0-nullsafety.11

dependency_overrides:
  # Required for null safety
  http:
    git: https://github.com/dart-lang/http.git
  http_parser: 4.0.0-nullsafety
  logging: ^1.0.0-nullsafety.0
